config/routes.rb
# -*- encoding : utf-8 -*-
Cybernetic::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root :to => 'welcome#index'
    get '/search', to: 'search#index'

    resources :pages, only: [:index, :show]
    resources :categories, only: [:show]
    resources :products, only: [:index, :show]
    resources :posts, only: [:index, :show]
    resources :contacts, only: [:new, :create]
    resources :faqs, only: [:index]
    resources :marketings, only: [:create]
    resources :downloads, only: [:index]
    resources :stores, only: [:show]

    namespace :admin do
      resources :pages, only: [:index, :show, :edit, :update]
      resources :sliders do
        collection { post :sort }
      end
      resources :categories do
        collection { post :sort }
      end
      resources :products
      resources :posts
      resources :contacts
      resources :faqs
      resources :films
      resources :downloads
      resources :stores
      resources :marketings
      resources :contacts
      resources :users do
        put '/approve', to: 'users#approve'
        put '/unapprove', to: 'users#unapprove'
      end
    end
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/views/admin/pages/_form.html.slim
= simple_form_for [:admin, @page], html: { class: 'form-horizontal' } do |f|
  = f.input :title, label: '標題', input_html: { class: 'span8' }
  = f.input :content, label: '內容', input_html: { class: 'span8 redactor' }
  .form-actions
    = f.submit '送出', class: 'btn btn-primary'

app/views/admin/pages/edit.html.slim
= render 'form'

app/views/admin/pages/index.html.slim
- content_for :page_title do
  h2.page-title.muted
    i.micon-paper
    | 所有靜態頁面

.row-fluid
  table.table.table-striped.table-bordered.table-condensed
    thead
      tr
        th 頁面
        th 更新於
        th 更新者
    tbody
      - @pages.each do |page|
        tr
          td= link_to page.title, edit_admin_page_path(page)
          td= l page.updated_at, format: '%Y-%m-%d %H:%M'
          td= page.user_email
  = will_paginate @pages