config/routes.rb
# -*- encoding : utf-8 -*-
Cybernetic::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root :to => 'welcome#index'
    get '/search', to: 'search#index'

    resources :pages, only: [:index, :show]
    resources :categories, only: [:show]
    resources :products, only: [:index, :show]
    resources :posts, only: [:index, :show]
    resources :contacts, only: [:new, :create]
    resources :faqs, only: [:index]
    resources :marketings, only: [:create]
    resources :downloads, only: [:index]
    resources :stores, only: [:show]

    namespace :admin do
      resources :pages, only: [:index, :show, :edit, :update]
      resources :sliders do
        collection { post :sort }
      end
      resources :categories do
        collection { post :sort }
      end
      resources :products
      resources :posts
      resources :contacts
      resources :faqs
      resources :films
      resources :downloads
      resources :stores
      resources :marketings
      resources :contacts
      resources :users do
        put '/approve', to: 'users#approve'
        put '/unapprove', to: 'users#unapprove'
      end
    end
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/controllers/welcome_controller.rb
# -*- encoding : utf-8 -*-
#encoding: utf-8
class WelcomeController < ApplicationController
  layout 'welcome'
  def index
    @sliders = Slider.where(block: "首頁橫幅廣告").order("position").include_locale(params[:locale])
    @news = Post.news.include_locale(params[:locale]).last(5)
    gon.newsTitle = I18n.t('menu.news')
  end
end

app/views/welcome/index.html.slim
= stylesheet_link_tag "welcome"
#welcome-index
  .content
    .container
      .row
        .span12
          /! Slider (Parallax Slider)
          #slider.carousel.slide data-interval="3000"
            .carousel-inner
              - @sliders.each_with_index do |slider, index|
                - if index == 0
                  .item.active
                    = link_to image_tag(slider.image_url(:slider_normal)), slider.target
                    - if slider.title.present?
                      .carousel-caption
                        h4= slider.title
                        = simple_format slider.description
                - else
                  .item
                    = link_to image_tag(slider.image_url(:slider_normal)), slider.target
                    - if slider.title.present?
                      .carousel-caption
                        h4= slider.title
                        = simple_format slider.description
            .slider-pager
              - @sliders.each_with_index do |slider, index|
                a href="#slider" #{index + 1}
      .row
        #news-block.span12
          - if @news.size > 0
            ul#news-index.js-hidden
              - @news.each do |post|
                li.news-item= link_to post.title, post_path(post)
      .row
        .span4
          = render_cell :widget, :block_ad, "首頁左下區塊"
        .span4
          = render_cell :widget, :block_ad, "首頁中下區塊"
        .span4
          .widget.article-content.rounded#welcome-news
            = render_cell :widget, :welcome_news
            /= render_cell :widget, :block_ad, "首頁右下區塊"