config/routes.rb
# -*- encoding : utf-8 -*-
Cybernetic::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root :to => 'welcome#index'
    get '/search', to: 'search#index'

    resources :pages, only: [:index, :show]
    resources :categories, only: [:show]
    resources :products, only: [:index, :show]
    resources :posts, only: [:index, :show]
    resources :contacts, only: [:new, :create]
    resources :faqs, only: [:index]
    resources :marketings, only: [:create]
    resources :downloads, only: [:index]
    resources :stores, only: [:show]

    namespace :admin do
      resources :pages, only: [:index, :show, :edit, :update]
      resources :sliders do
        collection { post :sort }
      end
      resources :categories do
        collection { post :sort }
      end
      resources :products
      resources :posts
      resources :contacts
      resources :faqs
      resources :films
      resources :downloads
      resources :stores
      resources :marketings
      resources :contacts
      resources :users do
        put '/approve', to: 'users#approve'
        put '/unapprove', to: 'users#unapprove'
      end
    end
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/models/category.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  c_image    :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  ancestry   :string(255)
#

class Category < ActiveRecord::Base
  attr_accessible :c_image, :title, :user, :user_id, :parent_id, :large_image,
                  :show_description, :en_large_image, :locales
  mount_uploader :c_image, CImageUploader
  mount_uploader :large_image, LargeImageUploader
  mount_uploader :en_large_image, EnLargeImageUploader
  serialize :locales, Array

  validates_presence_of :title
  belongs_to :user
  has_many :products
  before_destroy :set_products_category

  translates :title
  LOCALES = { "en" => '英文', "zh_tw" => "中文" }

  has_ancestry
  acts_as_list scope: [:ancestry]

  def set_products_category
    products.each do |product|
      product.set_category_to_uncategory
    end
  end

  def self.include_locale(locale)
    select {|m| m.locales.include?(locale)}
  end

end

app/controllers/admin/categories_controller.rb
# -*- encoding : utf-8 -*-
#encoding: utf-8
class Admin::CategoriesController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'

  def index
    @categories = Category.arrange(order: :position)
    @category = Category.new
  end

  def new
    @category = Category.new(:parent_id => params[:parent_id])
  end

  def sort
    params[:category].each_with_index do |id, index|
      Category.find(id).update(position: index + 1)
    end
    render nothing: true
  end

  def create
    @category = Category.new(params[:category])
    @category.user = current_user
    if @category.save
      redirect_to admin_categories_path, notice: "#{@category.title}新增成功"
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.user = current_user
    if @category.update_attributes(params[:category])
      redirect_to admin_categories_path, notice: "#{@category.title}更新成功"
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    title = @category.title
    @category.destroy
    redirect_to admin_categories_path, notice: "#{title}刪除成功"
  end

end

app/controllers/categories_controller.rb
# -*- encoding : utf-8 -*-
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    if @category.locales.include?(params[:locale])
      @category
      gon.active_id = @category.id
    else
      redirect_to root_path, notice: I18n.t('product.no_locale_for_this')
    end
  end
end

app/helpers/categories_helper.rb
# -*- encoding : utf-8 -*-
module CategoriesHelper

  def nested_categories(categories)
    categories.map do |category, sub_categories|
      render(category) + content_tag(:div, nested_categories(sub_categories), class: "nested_categories")
    end.join.html_safe
  end

  def suckerfish(categories)
	  categories.map do |category, sub_category|
	  	  content_tag :li, :id => dom_id(category), :class => cycle('odd', 'even') do
	  	  	render(category) + (content_tag(:ul, suckerfish(sub_category), class: 'unstyle sortable', data: { "update_url" => sort_admin_categories_url }) if sub_category.present?)
	  	  end
	  end.join.html_safe
	end

end

app/views/categories/_categories.html.slim
.row
  .span9
    = render_cell :widget, :categories_ads, [@category]
#showcase-divider
ul#categories
  - @category.children.each_slice(3) do |a, b, c|
    .row
      .product-images
        li
          .category
            h2= link_to a.title, category_path(a)
            .c_image
              = link_to image_tag(a.c_image_url(:large)), category_path(a)
        - if b
          li.second
            .category
              h2= link_to b.title, category_path(b)
              .c_image
                = link_to image_tag(b.c_image_url(:large)), category_path(b)
        - if c
          li.third
            .category
              h2= link_to c.title, category_path(c)
              .c_image
                = link_to image_tag(c.c_image_url(:large)), category_path(c)

app/views/categories/_products.html.slim
.row
  .span9
    = render_cell :widget, :categories_ads, [@category]
#showcase-divider
ul#products
  - @category.products.each_slice(3) do |a, b, c|
    .row
      .product-images
        li
          .product
            h2= link_to a.name, product_path(a)
            .p_image
              = link_to image_tag(a.feature_image(:large)), product_path(a)
            span= simple_format a.show_description
        - if b
          li.second
            .product
              h2= link_to b.name, product_path(b)
              .p_image
                = link_to image_tag(b.feature_image(:large)), product_path(b)
              span= simple_format b.show_description
        - if c
          li.third
            .product
              h2= link_to c.name, product_path(c)
              .p_image
                = link_to image_tag(c.feature_image(:large)), product_path(c)
              span= simple_format c.show_description

app/views/categories/show.html.slim
.row#categories-page
  .span3
    = render_cell :widget, :categories_sidebar
  .span9.article-content.rounded
    - if @category.has_children?
      = render 'categories'
    - else
      = render 'products'