config/routes.rb
# -*- encoding : utf-8 -*-
Cybernetic::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root :to => 'welcome#index'
    get '/search', to: 'search#index'

    resources :pages, only: [:index, :show]
    resources :categories, only: [:show]
    resources :products, only: [:index, :show]
    resources :posts, only: [:index, :show]
    resources :contacts, only: [:new, :create]
    resources :faqs, only: [:index]
    resources :marketings, only: [:create]
    resources :downloads, only: [:index]
    resources :stores, only: [:show]

    namespace :admin do
      resources :pages, only: [:index, :show, :edit, :update]
      resources :sliders do
        collection { post :sort }
      end
      resources :categories do
        collection { post :sort }
      end
      resources :products
      resources :posts
      resources :contacts
      resources :faqs
      resources :films
      resources :downloads
      resources :stores
      resources :marketings
      resources :contacts
      resources :users do
        put '/approve', to: 'users#approve'
        put '/unapprove', to: 'users#unapprove'
      end
    end
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.slim
footer
  .container
    .row
      .span4
        .copy
          p
            | Copyright © #{Time.now.year} #{I18n.t('brand')} #{I18n.t('right_reserve')}
      .span8
        = render_cell :widget, :marketing_footer
    .clearfix

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_menu.html.slim
.navbar#main-nav
  .navbar-inner
    .container
      a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
        span 目錄
      .nav-collapse.collapse
        ul.nav
          li= link_to "關於嘉亨", page_path("關於嘉亨")
          li.dropdown
            = link_to "#", class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
              | 產品資訊
            ul.dropdown-menu#mega-menu
              table
                tbody
                  - @categories.each_slice(4) do |a, b, c, d|
                    tr
                      td
                        .row-fluid
                          .span3
                            = image_tag a.c_image_url(:normal)
                          .span9
                            h4= a.title
                            - a.children.each do |child|
                              = link_to child.title, category_path(child)
                      - if b.present?
                        td
                          .row-fluid
                            .span3
                              = image_tag b.c_image_url(:normal)
                            .span9
                              h4= b.title
                              - b.children.each do |child|
                                = link_to child.title, category_path(child)
                      - if c.present?
                        td
                          .row-fluid
                            .span3
                              = image_tag c.c_image_url(:normal)
                            .span9
                              h4= c.title
                              - c.children.each do |child|
                                = link_to child.title, category_path(child)
                      - if d.present?
                        td
                          .row-fluid
                            .span3
                              = image_tag d.c_image_url(:normal)
                            .span9
                              h4= d.title
                              - d.children.each do |child|
                                = link_to child.title, category_path(child)
          li.dropdown
            =link_to "#", class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
              | 最新消息
            ul.dropdown-menu
              li= link_to "最新消息", posts_path(category: "最新消息")
              li= link_to "促銷活動", posts_path(category: "促銷活動")
          li.dropdown
            =link_to "#", class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
              | 經銷資訊
            ul.dropdown-menu
              li= link_to "獨立店", page_path("獨立店")
              li= link_to "3C賣場", page_path("3C賣場")
              li= link_to "生活賣場", page_path("生活賣場")
              li= link_to "網路賣場", page_path("網路賣場")
          li.dropdown
            =link_to "#", class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
              | 客戶服務
            ul.dropdown-menu
              li= link_to "產品註冊", page_path("產品註冊")
              li= link_to "聯絡客服", new_contact_path
              li= link_to "下載中心", page_path("下載中心")
              li= link_to "常見問題", faqs_path

app/views/common/_post_sidebar.html.slim
.sidebar.article-content.rounded.posts
  = render_cell :widget, :news_sidebar
  - if is_zh_tw?
    = render_cell :widget, :on_sale_sidebar

app/views/common/_search_form.html.erb
 <%= form_tag "/search", :class => "navbar-search", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
      
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">

    <li>
      <div class="social"> <%=  fb_like(Setting.domain) %>  </div>
    </li>

  <% if current_user %>    

    <li class="dropdown">
      <%= link_to "/account" , :class => "dropdown-toggle", :data => { :toggle => "dropdown" } do %>
        <%= current_user.email %>
      <% end %>

      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("Logout",destroy_user_session_path, :method => :delete )
      end %>

    </li>

<% else %>
  <li> <%= link_to( "Sing Up" ,new_user_registration_path) %> </li>
  <li> <%= link_to( "Login", new_user_session_path )  %> </li>   
<% end %>


</ul>